# a mybinder.org-ready environment for demoing jupyterlab_new_launcher
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-new-launcher-demo
#
name: jupyterlab-new-launcher-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.11.0a0
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=18,<19
  - nb_conda_kernels
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
